/**
 * Product AI Generator Plugin
 *
 * Adds a sidebar to generate product content via Gemini AI.
 */

import { registerPlugin } from '@wordpress/plugins';
import { PluginSidebar } from '@wordpress/edit-post';
import { Button, PanelBody, Spinner } from '@wordpress/components';
import { useSelect, useDispatch } from '@wordpress/data';
import apiFetch from '@wordpress/api-fetch';
import { useState } from '@wordpress/element';
// @ts-ignore
import { store as coreStore } from '@wordpress/core-data';
// @ts-ignore
import { store as noticesStore } from '@wordpress/notices';

const ProductAISidebar = () => {
    const [isGenerating, setIsGenerating] = useState(false);

    const { createNotice } = useDispatch(noticesStore);
    const { editPost } = useDispatch('core/editor');

    const { featuredImageUrl, productId, postType } = useSelect((select: any) => {
        const { getEditedPostAttribute, getCurrentPostId, getCurrentPostType } = select('core/editor');
        const mediaId = getEditedPostAttribute('featured_media');

        let url = null;
        if (mediaId) {
            const media = select(coreStore).getMedia(mediaId);
            url = media?.source_url;
        }

        return {
            featuredImageUrl: url,
            productId: getCurrentPostId(),
            postType: getCurrentPostType(),
        };
    }, []);

    // Only show on Product post type
    if (postType !== 'rk_product') {
        return null;
    }

    const handleGenerate = async () => {
        if (!featuredImageUrl) {
            createNotice('error', 'Please set a Featured Image first.');
            return;
        }

        setIsGenerating(true);

        try {
            const response: any = await apiFetch({
                path: '/renderkit/v1/ai/generate',
                method: 'POST',
                data: { imageUrl: featuredImageUrl },
            });

            if (response.title) {
                editPost({
                    title: response.title,
                    excerpt: response.excerpt,
                    content: response.description || '',
                    meta: {
                        _rk_price: response.price || '',
                        _rk_sale_price: response.sale_price || '',
                    }
                });
                createNotice('success', 'Product content generated by Gemini!');
            }
        } catch (error: any) {
            console.error(error);
            createNotice('error', error.message || 'AI Generation failed.');
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <PluginSidebar
            name="renderkit-product-ai"
            title="Product AI (Gemini)"
            icon="superhero"
        >
            <PanelBody title="Generate Content">
                <p style={{ marginBottom: 20 }}>
                    Automatically generate Titles, Excerpts, and Prices from your product image using Gemini 1.5 Flash.
                </p>

                {featuredImageUrl ? (
                    <div style={{ marginBottom: 20, borderRadius: 8, overflow: 'hidden' }}>
                        <img
                            src={featuredImageUrl}
                            alt="Preview"
                            style={{ display: 'block', width: '100%', height: 'auto', opacity: isGenerating ? 0.5 : 1 }}
                        />
                    </div>
                ) : (
                    <p style={{ color: '#b32d2e', marginBottom: 20 }}>
                        ⚠️ No Featured Image selected.
                    </p>
                )}

                <button
                    className="components-button is-primary"
                    onClick={handleGenerate}
                    disabled={isGenerating || !featuredImageUrl}
                    style={{
                        width: '100%',
                        justifyContent: 'center',
                        height: '36px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px'
                    }}
                >
                    {isGenerating ? (
                        <>
                            <Spinner /> Generating...
                        </>
                    ) : (
                        '✨ Magic Generate'
                    )}
                </button>

                <p style={{ fontSize: 11, color: '#666', marginTop: 10, textAlign: 'center' }}>
                    Powered by Google Gemini
                </p>
            </PanelBody>
        </PluginSidebar>
    );
};

registerPlugin('renderkit-product-ai', {
    render: ProductAISidebar,
    icon: 'superhero'
});
